name: Build and Release App

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            VERSION: "1.0.${{ github.run_number }}"

        steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Setup .NET SDK
          uses: actions/setup-dotnet@v3
          with:
            dotnet-version: 8.0.x

        - name: Restore dependencies
          run: dotnet restore

        - name: Build
          run: dotnet build --configuration Release --no-restore

        # Publish if the branch is main and not a pull request
        - name: Publish
          if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
          run: dotnet publish --configuration Release --output ./publish
        
        # Zip the published app
        - name: Zip
          if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
          run: zip -r mealplannerweb-${{ env.VERSION }}.zip ./publish/*

        # Create a release
        - name: Create Release
          if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
          uses: softprops/action-gh-release@v1
          with:
            files: ./mealplannerweb-${{ env.VERSION }}.zip
            token: ${{ secrets.GITHUB_TOKEN }}
            tag_name: ${{ env.VERSION }}
            body: "Release ${{ env.VERSION }}"

        